<a href="https://colab.research.google.com/github/juanmadeira/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. [PyTorch Fundamentals](https://www.learnpytorch.io/00_pytorch_fundamentals)
## Deep Learning
>_"If you can build a *simple rule-based* system that doesn't require machine learning, do that."_
— A wise software engineer... (actually rule 1 of [Google's Machine Learning Handbook](https://developers.google.com/machine-learning/guides/rules-of-ml?hl=pt-br#rule_1_don%E2%80%99t_be_afraid_to_launch_a_product_without_machine_learning))

### What deep learning is good for
- Problems with long lists of rules
- Continually changing environments
- Discovering insights within large collections of data

### What deep learning is NOT good for
- When you need explainability
- When the traditional approach is a better option
- When errors are unacceptable
- When you don't have much data

In [213]:
import torch

print(torch.__version__)

2.6.0+cu124


## Tensors
[What is a tensor?](https://youtu.be/f5liqUk0ZTw)


### Creating a tensor
[`torch.tensor()`](https://docs.pytorch.org/docs/stable/tensors.html)

In [214]:
# scalar
scalar = torch.tensor(7)

scalar

tensor(7)

In [215]:
scalar.ndim

0

In [216]:
# get tensor back as python int
scalar.item()

7

In [217]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [218]:
vector.ndim

1

In [219]:
vector.shape

torch.Size([2])

In [220]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [221]:
MATRIX.ndim

2

In [222]:
MATRIX[0]

tensor([7, 8])

In [223]:
MATRIX.shape

torch.Size([2, 2])

In [224]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [225]:
TENSOR.ndim

3

In [226]:
TENSOR.shape

torch.Size([1, 3, 3])

In [227]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### [Random tensors](https://docs.pytorch.org/docs/stable/generated/torch.rand.html)
A maneira com que muitas redes neurais aprendem é com tensores cheios de números aleatórios e, então, ajustam esses números para representar a informação de forma adequada.

`random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [228]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2224, 0.4434, 0.2441, 0.3252],
        [0.7899, 0.9902, 0.1312, 0.6209],
        [0.8033, 0.3050, 0.2935, 0.3369]])

In [229]:
random_tensor.ndim

2

In [230]:
# create a random tensor with similar shape to and image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [231]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))

In [232]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [233]:
# create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [234]:
zeros.dtype

torch.float32

In [235]:
ones.dtype

torch.float32

In [236]:
random_tensor.dtype

torch.float32

### Range of tensors and tensors-like

In [237]:
# torch.range()
torch.range(0, 10) # deprecated

/tmp/ipython-input-237-3619803812.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10) # deprecated


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [238]:
# torch.arange()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [239]:
one_to_fifty = torch.arange(start=1, end=50, step=2)
one_to_fifty

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49])

In [240]:
one_to_fifty_zeros = torch.zeros_like(input=one_to_fifty)
one_to_fifty_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0])

### Tensor datatypes
32-bit floating point: `torch.float32` or `torch.float`\
64-bit floating point: `torch.float64` or `torch.double`\
16-bit floating point: `torch.float16` or `torch.half`

>Troubleshooting:

1. Tensors not right datatype - `tensor.dtype`
2. Tensors not right shape - `tensor.shape`
3. Tensors not on the right device - `tensor.device`

In [241]:
# float32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # datatype (float32, float16)
                               device="cpu", # "cuda" for GPU
                               requires_grad=False) # track gradients
float_32_tensor

tensor([3., 6., 9.])

In [242]:
float_32_tensor.dtype

torch.float32

In [243]:
float_16_tensor = float_32_tensor.type(torch.float16) # or torch.half
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [244]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [245]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [246]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Tensor attributes
[torch.dtype](https://docs.pytorch.org/docs/stable/tensor_attributes.html#torch-dtype)\
[torch.device](https://docs.pytorch.org/docs/stable/tensor_attributes.html#torch-device)\
[torch.layout](https://docs.pytorch.org/docs/stable/tensor_attributes.html#torch-layout)

In [247]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1538, 0.2202, 0.5325, 0.7469],
        [0.3208, 0.3039, 0.8236, 0.0662],
        [0.9397, 0.3025, 0.1649, 0.8288]])

In [248]:
# details about some tensor
print(some_tensor)
print(f"\nDatatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")
print(f"Layout of tensor: {some_tensor.layout}")

tensor([[0.1538, 0.2202, 0.5325, 0.7469],
        [0.3208, 0.3039, 0.8236, 0.0662],
        [0.9397, 0.3025, 0.1649, 0.8288]])

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu
Layout of tensor: torch.strided


### Tensor operations

- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [249]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [250]:
tensor + 10 # or torch.add(tensor, 10)

tensor([11, 12, 13])

In [251]:
tensor - 10

tensor([-9, -8, -7])

In [252]:
tensor * 10 # or torch.mul(tensor, 10)

tensor([10, 20, 30])

In [253]:
tensor / 10 # or torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])