<a href="https://colab.research.google.com/github/juanmadeira/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. [PyTorch Fundamentals](https://www.learnpytorch.io/00_pytorch_fundamentals)
## Deep Learning
>_"If you can build a *simple rule-based* system that doesn't require machine learning, do that."_
— A wise software engineer... (actually rule 1 of [Google's Machine Learning Handbook](https://developers.google.com/machine-learning/guides/rules-of-ml?hl=pt-br#rule_1_don%E2%80%99t_be_afraid_to_launch_a_product_without_machine_learning))

### What deep learning is good for
- Problems with long lists of rules
- Continually changing environments
- Discovering insights within large collections of data

### What deep learning is NOT good for
- When you need explainability
- When the traditional approach is a better option
- When errors are unacceptable
- When you don't have much data

In [82]:
import torch

print(torch.__version__)

2.6.0+cu124


# Tensors
[What is a tensor?](https://youtu.be/f5liqUk0ZTw)

## Creating a tensor
[`torch.tensor()`](https://docs.pytorch.org/docs/stable/tensors.html)

In [83]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [84]:
scalar.ndim

0

In [85]:
# get tensor back as python int
scalar.item()

7

In [86]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [87]:
vector.ndim

1

In [88]:
vector.shape

torch.Size([2])

In [89]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [90]:
MATRIX.ndim

2

In [91]:
MATRIX[0]

tensor([7, 8])

In [92]:
MATRIX.shape

torch.Size([2, 2])

In [93]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [94]:
TENSOR.ndim

3

In [95]:
TENSOR.shape

torch.Size([1, 3, 3])

In [96]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### [Random tensors](https://docs.pytorch.org/docs/stable/generated/torch.rand.html)
A maneira com que muitas redes neurais aprendem é com tensores cheios de números aleatórios e, então, ajustam esses números para representar a informação de forma adequada.

`random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [97]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [98]:
random_tensor.ndim

2

In [99]:
# create a random tensor with similar shape to and image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [100]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))

In [101]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [102]:
# create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [103]:
zeros.dtype

torch.float32

In [104]:
ones.dtype

torch.float32

In [105]:
random_tensor.dtype

torch.float32

### Range of tensors and tensors-like

In [106]:
# torch.range()
torch.range(0, 10) # deprecated

/tmp/ipython-input-106-3619803812.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10) # deprecated


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [107]:
# torch.arange()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
one_to_fifty = torch.arange(start=1, end=50, step=2)
one_to_fifty

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49])

In [109]:
one_to_fifty_zeros = torch.zeros_like(input=one_to_fifty)
one_to_fifty_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0])

## Tensor datatypes
32-bit floating point: `torch.float32` or `torch.float`\
64-bit floating point: `torch.float64` or `torch.double`\
16-bit floating point: `torch.float16` or `torch.half`

>Troubleshooting:

1. Tensors not right datatype - `tensor.dtype`
2. Tensors not right shape - `tensor.shape`
3. Tensors not on the right device - `tensor.device`

In [110]:
# float32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # datatype (float32, float16)
                               device="cpu", # "cuda" for GPU
                               requires_grad=False) # track gradients
float_32_tensor

tensor([3., 6., 9.])

In [111]:
float_32_tensor.dtype

torch.float32

In [112]:
float_16_tensor = float_32_tensor.type(torch.float16) # or torch.half
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [113]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [114]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [115]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Tensor attributes
[torch.dtype](https://docs.pytorch.org/docs/stable/tensor_attributes.html#torch-dtype)\
[torch.device](https://docs.pytorch.org/docs/stable/tensor_attributes.html#torch-device)\
[torch.layout](https://docs.pytorch.org/docs/stable/tensor_attributes.html#torch-layout)

In [116]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5745, 0.9200, 0.3230, 0.8613],
        [0.0919, 0.3102, 0.9536, 0.6002],
        [0.0351, 0.6826, 0.3743, 0.5220]])

In [117]:
# details about some tensor
print(some_tensor)
print(f"\nDatatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")
print(f"Layout of tensor: {some_tensor.layout}")

tensor([[0.5745, 0.9200, 0.3230, 0.8613],
        [0.0919, 0.3102, 0.9536, 0.6002],
        [0.0351, 0.6826, 0.3743, 0.5220]])

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu
Layout of tensor: torch.strided


## Tensor operations

- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [118]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [119]:
tensor + 10 # or torch.add(tensor, 10)

tensor([11, 12, 13])

In [120]:
tensor - 10

tensor([-9, -8, -7])

In [121]:
tensor * tensor # or torch.mul(tensor, tensor)

tensor([1, 4, 9])

In [122]:
tensor / 10 # or torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

#### Matrix multiplication
1. The **inner dimensions** must match
- `(3, 2) @ (3, 2)` won't work
- `(3, 2) @ (2, 3)` will work
- `(2, 3) @ (3, 2)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
- `(2, 3) @ (3, 2)` -> `(2, 2)`
- `(3, 2) @ (2, 3)` -> `(3, 3)`

In [123]:
torch.matmul(tensor, tensor) # or torch.mm or tensor @ tensor

tensor(14)

In [124]:
1*1 + 2*2 + 3*3

14

In [125]:
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

value

tensor(14)

##### Shape errors

In [126]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.matmul(tensor_A, tensor_B)

# RuntimeError                              Traceback (most recent call last)
# /tmp/ipython-input-242-2293279752.py in <cell line: 0>()
#       7                          [9, 12]])
#       8
# ----> 9 torch.matmul(tensor_A, tensor_B)
# RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [127]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [128]:
# transpose switches the axes or dimensions of a given tensor
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [129]:
# the matrix multiplication operation works when tensor_B is transposed
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [130]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])


## Tensor agregation
Finding the min, max, mean, sum etc.

In [131]:
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [132]:
# find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [133]:
# find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [134]:
# find the mean

# the mean() function requires a tensor of float32 datatype
# torch.mean(x) will return "RuntimeError: mean(): could not infer output dtype"

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [135]:
# find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [136]:
# find the position in tensor that has the minimum value with argmin()
# (returns index position of target tensor where the minium value occurs)
x.argmin(), x[0]

(tensor(0), tensor(1))

In [137]:
# find the position in tensor that has the maximum value with argmax()
x.argmax(), x[9]

(tensor(9), tensor(91))

## Reshaping, stacking, squeezing, unsqueezing and permutting

In [138]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [139]:
# reshaping: reshapes and input tensor to a defined shape
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [140]:
# view: return a view of an input tensor of certain shape
z = x.view(1, 9)
z, z.shape, x, x.shape # changing z changes x (because a view of a tensor share the same memory as the original tensor)

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]))

In [141]:
# stacking: combine multiple tensors on top of each other (vstack) or side by side (hstack)
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [142]:
# squeeze: remove all `1` dimensions from a tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze() # remove extra dimensions from x_reshaped

print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape: torch.Size([9, 1])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [143]:
# unsqueeze: add `1` dimension to a target tensor
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0) # add an extra dimension
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [144]:
# permute: return a view of the input with dimensions permuted (swapped) in a certain way
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0 , 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [145]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [146]:
x[0][0] # indexing the middle bracket (dim=1)

tensor([1, 2, 3])

In [147]:
x[0][0][0] # indexing the most inner bracker (last dimension)

tensor(1)

In [148]:
x[:, 0] # : to select "all" of a target dimension

tensor([[1, 2, 3]])

In [149]:
x[:, :, 1] # get all values of 0th and 1st dimensions but only index 1st of 2nd dimensions

tensor([[2, 5, 8]])

In [150]:
x[:, 1, 1] # get all values of the 0th dimension but only the 1 index value of 1st and 2nd dimensions

tensor([5])

In [151]:
x[0, 0, :] # get index 0 of 0th and 1st dimension and all values of 2nd dimension

tensor([1, 2, 3])

## PyTorch Tensors & NumPy
* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

> When converting from NumPy to PyTorch, PyTorch reflects NumPy's default datatype of float64 unless specified otherwise (default is float32)

In [152]:
# NumPy array to tensor
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [153]:
array = array + 1
array, tensor # doesn't share memory

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [154]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
numpy_tensor, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([1., 1., 1., 1., 1., 1., 1.]))

In [155]:
tensor = tensor + 1
numpy_tensor, tensor # doesn't share memory as well

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2.]))

## [Reproducibility](https://docs.pytorch.org/docs/stable/notes/randomness.html) (trying to take random out of random)

`start with random numbers -> tensor operations -> update random numbers to try and make better representation of the data -> again...`

More about [random seed](https://www.w3schools.com/python/ref_random_seed.asp).

In [156]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5888, 0.8403, 0.4761, 0.7140],
        [0.4644, 0.6362, 0.8892, 0.1317],
        [0.7164, 0.2706, 0.6560, 0.6614]])
tensor([[0.3648, 0.1490, 0.8693, 0.0294],
        [0.5449, 0.0794, 0.2313, 0.2927],
        [0.3386, 0.3708, 0.0831, 0.0944]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [157]:
# now random but reproducible tensors
RANDOM_SEED = 42 # "flavour of randomness" (42 is a arbitrary value)

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Runing PyTorch on the GPUs

1. Easiest: Google Colab
2. Use your own GPU
3. Cloud computing (GCP, AWS, Azure etc.)

For **2** and **3** read the [documentation](https://pytorch.org/get-started/locally/) and [best practices](https://docs.pytorch.org/docs/stable/notes/cuda.html#best-practices).

In [158]:
# check for GPU access with PyTorch
torch.cuda.is_available()

True

In [159]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [160]:
# count number of devices
torch.cuda.device_count()

1

### Runnning tensors (and models) on the GPU

In [161]:
tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device) # default on the CPU

tensor([1, 2, 3]) cpu


In [162]:
# move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [164]:
# if tensor is on GPU, can't transform it to NumPy
# tensor_on_gpu.numpy()

# TypeError                                 Traceback (most recent call last)
# /tmp/ipython-input-163-3488454448.py in <cell line: 0>()
#       1 # if tensor is on GPU, can't transform it to NumPy
# ----> 2 tensor_on_gpu.numpy()
# TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [165]:
# to fix the GPU with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [166]:
tensor_on_gpu # remains unchanged

tensor([1, 2, 3], device='cuda:0')