<a href="https://colab.research.google.com/github/juanmadeira/pytorch/blob/main/00_pytorch_fundamentos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. [Fundamentos do PyTorch](https://www.learnpytorch.io/00_pytorch_fundamentals)

In [36]:
import torch

print(torch.__version__)

2.6.0+cu124


## Tensores
`torch.tensor()`

In [37]:
# scalar
scalar = torch.tensor(7)

scalar

tensor(7)

In [38]:
scalar.ndim

0

In [39]:
# get tensor back as python int
scalar.item()

7

In [40]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [41]:
vector.ndim

1

In [42]:
vector.shape

torch.Size([2])

In [43]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [44]:
MATRIX.ndim

2

In [45]:
MATRIX[0]

tensor([7, 8])

In [46]:
MATRIX.shape

torch.Size([2, 2])

In [47]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [48]:
TENSOR.ndim

3

In [49]:
TENSOR.shape

torch.Size([1, 3, 3])

In [50]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### [Random tensors](https://docs.pytorch.org/docs/stable/generated/torch.rand.html)
A maneira com que muitas redes neurais aprendem é com tensores cheios de números aleatórios e, então, ajustam esses números para representar a informação de forma adequada.

`random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [59]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8499, 0.1389, 0.9723, 0.6511],
        [0.8798, 0.5586, 0.8627, 0.3526],
        [0.1467, 0.8162, 0.6377, 0.7941]])

In [52]:
random_tensor.ndim

2

In [54]:
# create a random tensor with similar shape to and image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [82]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))

In [77]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [78]:
# create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [79]:
zeros.dtype

torch.float32

In [80]:
ones.dtype

torch.float32

In [81]:
random_tensor.dtype

torch.float32

### Range of tensors and tensors-like

In [104]:
# torch.range()
torch.range(0, 10) # deprecated

/tmp/ipython-input-104-3619803812.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10) # deprecated


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [74]:
# torch.arange()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
one_to_fifty = torch.arange(start=1, end=50, step=2)
one_to_fifty

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49])

In [102]:
one_to_fifty_zeros = torch.zeros_like(input=one_to_fifty)
one_to_fifty_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0])

### Tensor datatypes

In [107]:
# float32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [108]:
float_32_tensor.dtype

torch.float32