<a href="https://colab.research.google.com/github/juanmadeira/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. [PyTorch Fundamentals](https://www.learnpytorch.io/00_pytorch_fundamentals)
## Deep Learning
>_"If you can build a *simple rule-based* system that doesn't require machine learning, do that."_
— A wise software engineer... (actually rule 1 of [Google's Machine Learning Handbook](https://developers.google.com/machine-learning/guides/rules-of-ml?hl=pt-br#rule_1_don%E2%80%99t_be_afraid_to_launch_a_product_without_machine_learning))

### What deep learning is good for
- Problems with long lists of rules
- Continually changing environments
- Discovering insights within large collections of data

### What deep learning is NOT good for
- When you need explainability
- When the traditional approach is a better option
- When errors are unacceptable
- When you don't have much data

In [454]:
import torch

print(torch.__version__)

2.6.0+cu124


## Tensors
[What is a tensor?](https://youtu.be/f5liqUk0ZTw)


### Creating a tensor
[`torch.tensor()`](https://docs.pytorch.org/docs/stable/tensors.html)

In [455]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [456]:
scalar.ndim

0

In [457]:
# get tensor back as python int
scalar.item()

7

In [458]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [459]:
vector.ndim

1

In [460]:
vector.shape

torch.Size([2])

In [461]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [462]:
MATRIX.ndim

2

In [463]:
MATRIX[0]

tensor([7, 8])

In [464]:
MATRIX.shape

torch.Size([2, 2])

In [465]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [466]:
TENSOR.ndim

3

In [467]:
TENSOR.shape

torch.Size([1, 3, 3])

In [468]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### [Random tensors](https://docs.pytorch.org/docs/stable/generated/torch.rand.html)
A maneira com que muitas redes neurais aprendem é com tensores cheios de números aleatórios e, então, ajustam esses números para representar a informação de forma adequada.

`random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [469]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2998, 0.9474, 0.5419, 0.0787],
        [0.6596, 0.0447, 0.6748, 0.8490],
        [0.3029, 0.0713, 0.5163, 0.5470]])

In [470]:
random_tensor.ndim

2

In [471]:
# create a random tensor with similar shape to and image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [472]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))

In [473]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [474]:
# create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [475]:
zeros.dtype

torch.float32

In [476]:
ones.dtype

torch.float32

In [477]:
random_tensor.dtype

torch.float32

### Range of tensors and tensors-like

In [478]:
# torch.range()
torch.range(0, 10) # deprecated

/tmp/ipython-input-478-3619803812.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10) # deprecated


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [479]:
# torch.arange()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [480]:
one_to_fifty = torch.arange(start=1, end=50, step=2)
one_to_fifty

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49])

In [481]:
one_to_fifty_zeros = torch.zeros_like(input=one_to_fifty)
one_to_fifty_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0])

### Tensor datatypes
32-bit floating point: `torch.float32` or `torch.float`\
64-bit floating point: `torch.float64` or `torch.double`\
16-bit floating point: `torch.float16` or `torch.half`

>Troubleshooting:

1. Tensors not right datatype - `tensor.dtype`
2. Tensors not right shape - `tensor.shape`
3. Tensors not on the right device - `tensor.device`

In [482]:
# float32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # datatype (float32, float16)
                               device="cpu", # "cuda" for GPU
                               requires_grad=False) # track gradients
float_32_tensor

tensor([3., 6., 9.])

In [483]:
float_32_tensor.dtype

torch.float32

In [484]:
float_16_tensor = float_32_tensor.type(torch.float16) # or torch.half
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [485]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [486]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [487]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Tensor attributes
[torch.dtype](https://docs.pytorch.org/docs/stable/tensor_attributes.html#torch-dtype)\
[torch.device](https://docs.pytorch.org/docs/stable/tensor_attributes.html#torch-device)\
[torch.layout](https://docs.pytorch.org/docs/stable/tensor_attributes.html#torch-layout)

In [488]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3885, 0.9340, 0.5979, 0.8688],
        [0.4382, 0.6132, 0.9345, 0.5582],
        [0.3956, 0.6182, 0.3388, 0.1993]])

In [489]:
# details about some tensor
print(some_tensor)
print(f"\nDatatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")
print(f"Layout of tensor: {some_tensor.layout}")

tensor([[0.3885, 0.9340, 0.5979, 0.8688],
        [0.4382, 0.6132, 0.9345, 0.5582],
        [0.3956, 0.6182, 0.3388, 0.1993]])

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu
Layout of tensor: torch.strided


### Tensor operations

- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [490]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [491]:
tensor + 10 # or torch.add(tensor, 10)

tensor([11, 12, 13])

In [492]:
tensor - 10

tensor([-9, -8, -7])

In [493]:
tensor * tensor # or torch.mul(tensor, tensor)

tensor([1, 4, 9])

In [494]:
tensor / 10 # or torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

#### Matrix multiplication
1. The **inner dimensions** must match
- `(3, 2) @ (3, 2)` won't work
- `(3, 2) @ (2, 3)` will work
- `(2, 3) @ (3, 2)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
- `(2, 3) @ (3, 2)` -> `(2, 2)`
- `(3, 2) @ (2, 3)` -> `(3, 3)`

In [495]:
torch.matmul(tensor, tensor) # or torch.mm or tensor @ tensor

tensor(14)

In [496]:
1*1 + 2*2 + 3*3

14

In [497]:
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

value

tensor(14)

##### Shape errors

In [498]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [499]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [508]:
# transpose switches the axes or dimensions of a given tensor
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [509]:
# the matrix multiplication operation works when tensor_B is transposed
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")