<a href="https://colab.research.google.com/github/juanmadeira/pytorch/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

> 1. Documentation reading.

In [85]:
import torch

> 2. Create a random tensor with shape (7, 7).

In [86]:
tensor1 = torch.rand(size=(7, 7))
print(f"{tensor1}\n\n{tensor1.shape}")

tensor([[0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593, 0.7204],
        [0.0731, 0.9699, 0.1078, 0.8829, 0.4132, 0.7572, 0.6948],
        [0.5209, 0.5932, 0.8797, 0.6286, 0.7653, 0.1132, 0.8559],
        [0.6721, 0.6267, 0.5691, 0.7437, 0.9592, 0.3887, 0.2214],
        [0.3742, 0.1953, 0.7405, 0.2529, 0.2332, 0.9314, 0.9575],
        [0.5575, 0.4134, 0.4355, 0.7369, 0.0331, 0.0914, 0.8994],
        [0.9936, 0.4703, 0.1049, 0.5137, 0.2674, 0.4990, 0.7447]])

torch.Size([7, 7])


> 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [87]:
tensor2 = torch.rand(size=(1, 7))
tensor2 = tensor2.T # transposing second tensor

torch.matmul(tensor1, tensor2)

tensor([[1.6914],
        [1.7581],
        [2.0906],
        [1.8975],
        [1.7585],
        [1.7961],
        [1.8900]])

> 4. Set the random seed to 0 and do exercises 2 & 3 over again.

In [88]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
tensor1 = torch.rand(size=(7,7))
torch.manual_seed(RANDOM_SEED)
tensor2 = torch.rand(size=(1,7))
tensor2 = tensor2.T

torch.matmul(tensor1, tensor2)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

> 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [89]:
print(f"GPU access: {torch.cuda.is_available()}")
device = "cuda" if torch.cuda.is_available() else "cpu"

torch.cuda.manual_seed(1234)

GPU access: True


> 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [90]:
torch.manual_seed(1234)
tensor1 = torch.rand(size=(2, 3))
torch.manual_seed(1234)
tensor2 = torch.rand(size=(2, 3))

tensor1 = tensor1.to(device)
tensor2 = tensor2.to(device)

print(f"{tensor1}\n\n{tensor1.shape}\n\n")
print(f"{tensor2}\n\n{tensor2.shape}")

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')

torch.Size([2, 3])


tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')

torch.Size([2, 3])


> 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [91]:
tensor2 = tensor2.T

result = torch.matmul(tensor1, tensor2)
print(f"{result}\n\n{result.shape}")

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

torch.Size([2, 2])


> 8. Find the maximum and minimum values of the output of 7.

In [92]:
result.max(), result.min()

(tensor(0.6287, device='cuda:0'), tensor(0.2161, device='cuda:0'))

> 9. Find the maximum and minimum index values of the output of 7.

In [93]:
result.argmax(), result.argmin()

(tensor(3, device='cuda:0'), tensor(1, device='cuda:0'))

> 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [94]:
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)
tensor1 = torch.rand(size=(1, 1, 1, 10))
tensor2 = tensor1.squeeze()

print(f"{tensor1}\n\n{tensor1.shape}\n\n")
print(f"{tensor2}\n\n{tensor2.shape}")

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])

torch.Size([1, 1, 1, 10])


tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])

torch.Size([10])
