<a href="https://colab.research.google.com/github/juanmadeira/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. [PyTorch Fundamentals](https://www.learnpytorch.io/00_pytorch_fundamentals)
## Deep Learning
>_"If you can build a *simple rule-based* system that doesn't require machine learning, do that."_
— A wise software engineer... (actually rule 1 of [Google's Machine Learning Handbook](https://developers.google.com/machine-learning/guides/rules-of-ml?hl=pt-br#rule_1_don%E2%80%99t_be_afraid_to_launch_a_product_without_machine_learning))

### What deep learning is good for
- Problems with long lists of rules
- Continually changing environments
- Discovering insights within large collections of data

### What deep learning is NOT good for
- When you need explainability
- When the traditional approach is a better option
- When errors are unacceptable
- When you don't have much data

In [ ]:
import torch

print(torch.__version__)

2.6.0+cu124


# Tensors
[What is a tensor?](https://youtu.be/f5liqUk0ZTw)

## Creating a tensor
[`torch.tensor()`](https://docs.pytorch.org/docs/stable/tensors.html)

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### [Random tensors](https://docs.pytorch.org/docs/stable/generated/torch.rand.html)
A maneira com que muitas redes neurais aprendem é com tensores cheios de números aleatórios e, então, ajustam esses números para representar a informação de forma adequada.

`random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7536, 0.4431, 0.8748, 0.6822],
        [0.8738, 0.5804, 0.3357, 0.8351],
        [0.3838, 0.0787, 0.3915, 0.2927]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# create a random tensor with similar shape to and image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))

In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
zeros.dtype

torch.float32

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### Range of tensors and tensors-like

In [ ]:
# torch.range()
torch.range(0, 10) # deprecated

/tmp/ipython-input-97-3619803812.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10) # deprecated


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# torch.arange()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_fifty = torch.arange(start=1, end=50, step=2)
one_to_fifty

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49])

In [ ]:
one_to_fifty_zeros = torch.zeros_like(input=one_to_fifty)
one_to_fifty_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0])

## Tensor datatypes
32-bit floating point: `torch.float32` or `torch.float`\
64-bit floating point: `torch.float64` or `torch.double`\
16-bit floating point: `torch.float16` or `torch.half`

>Troubleshooting:

1. Tensors not right datatype - `tensor.dtype`
2. Tensors not right shape - `tensor.shape`
3. Tensors not on the right device - `tensor.device`

In [ ]:
# float32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # datatype (float32, float16)
                               device="cpu", # "cuda" for GPU
                               requires_grad=False) # track gradients
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16) # or torch.half
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Tensor attributes
[torch.dtype](https://docs.pytorch.org/docs/stable/tensor_attributes.html#torch-dtype)\
[torch.device](https://docs.pytorch.org/docs/stable/tensor_attributes.html#torch-device)\
[torch.layout](https://docs.pytorch.org/docs/stable/tensor_attributes.html#torch-layout)

In [ ]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1610, 0.1885, 0.3775, 0.2670],
        [0.0235, 0.3513, 0.1400, 0.7960],
        [0.4163, 0.6089, 0.6486, 0.4065]])

In [ ]:
# details about some tensor
print(some_tensor)
print(f"\nDatatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")
print(f"Layout of tensor: {some_tensor.layout}")

tensor([[0.1610, 0.1885, 0.3775, 0.2670],
        [0.0235, 0.3513, 0.1400, 0.7960],
        [0.4163, 0.6089, 0.6486, 0.4065]])

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu
Layout of tensor: torch.strided


## Tensor operations

- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [ ]:
tensor + 10 # or torch.add(tensor, 10)

tensor([11, 12, 13])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
tensor * tensor # or torch.mul(tensor, tensor)

tensor([1, 4, 9])

In [ ]:
tensor / 10 # or torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

#### Matrix multiplication
1. The **inner dimensions** must match
- `(3, 2) @ (3, 2)` won't work
- `(3, 2) @ (2, 3)` will work
- `(2, 3) @ (3, 2)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
- `(2, 3) @ (3, 2)` -> `(2, 2)`
- `(3, 2) @ (2, 3)` -> `(3, 3)`

In [ ]:
torch.matmul(tensor, tensor) # or torch.mm or tensor @ tensor

tensor(14)

In [ ]:
1*1 + 2*2 + 3*3

14

In [ ]:
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

value

tensor(14)

##### Shape errors

In [ ]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
# transpose switches the axes or dimensions of a given tensor
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
# the matrix multiplication operation works when tensor_B is transposed
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])


## Tensor agregation
Finding the min, max, mean, sum etc.

In [ ]:
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
# find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
# find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
# find the mean

# the mean() function requires a tensor of float32 datatype
# torch.mean(x) will return "RuntimeError: mean(): could not infer output dtype"

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
# find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [ ]:
# find the position in tensor that has the minimum value with argmin()
# (returns index position of target tensor where the minium value occurs)
x.argmin(), x[0]

In [ ]:
# find the position in tensor that has the maximum value with argmax()
x.argmax(), x[9]

(tensor(9), tensor(91))